# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('img', models.CharField(default='axf.png', max_length=20)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': '7+2_user',
            },
        ),
    ]
