# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojectApp', '0002_auto_20190116_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img1', models.CharField(max_length=256)),
                ('img2', models.CharField(max_length=256)),
                ('img3', models.CharField(max_length=256)),
                ('img4', models.CharField(max_length=256)),
                ('img5', models.CharField(max_length=256)),
                ('img6', models.CharField(max_length=256)),
                ('img7', models.CharField(max_length=256)),
            ],
        ),
    ]
